### PR TITLE
Upgrade to google-protobuf 3.6.1 to support proto3 messages

### PR DESCRIPTION
**Pull request by mohamabid**
Hi, Wanted to continue using the library to serialize our proto3 messages. Change Should continue to support proto2 messages.

Let me know if you want me to make any changes or discuss. Open to making more contributions.

Thanks,
Abid

### CODE REVIEW

**Comment by mohamabid** [comment]
@magro 
can you take a look when you get a chance. Thanks.

**Comment by magro** [comment]
@mohamabid what happens to users of protobuf-java 2.x?

**Comment by mohamabid** [comment]
@magro 
As we now expect messages to extend com.google.protobuf.AbstractMessage which was present in protobuf-Java 2.x, this change should not affect users of 2.x

**Comment by magro** [comment]
Great, sounds good then!

**Comment by mohamabid** [comment]
@magro 
Thanks!

**Pull request merged**
