### PR TITLE
Add support for Guava's ReverseList.

### PR DESCRIPTION
**Pull request by amitsela**
Supporting Guava's [ReverseList](https://github.com/google/guava/blob/v17.0/guava/src/com/google/common/collect/Lists.java#L763) (and [RandomAccessReverseList](https://github.com/google/guava/blob/v17.0/guava/src/com/google/common/collect/Lists.java#L883)).
First time writing a Kryo serializer, appreciate the feedback.
Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/magro/kryo-serializers/55)

### CODE REVIEW

**Comment by amitsela** [comment]
R: @magro

**Comment by magro** [comment]
Thanks for the PR, I just released it with 0.39.

**Comment by amitsela** [comment]
Great! happy to hear that.

**Comment by magro** [comment]
Btw, I also just updated the kryo dependency to 4.0.0 and released kryo-serializers 0.40 with this.

**Comment by amitsela** [comment]
I'm mostly using Kryo with Spark so I assume that might not play nicely together 😉.

**Comment by magro** [comment]
Ah ok, might take a bit, as long as you cannot change the used kryo version on your own...

**Comment by amitsela** [comment]
@magro quick question - can I use version `0.39` with Twitter `chill-0.5.0` (depends on `kryo-2.21`) ? or should I use the latest `0.2x` ? thanks.

**Comment by magro** [comment]
@amitsela Hmm, not sure, you could give it a try. If course you'd have to exclude the kryo dependency from kryo-serializers to stay with kryo 2.21.

**Comment by amitsela** [comment]
Yeah, did that, just worried about backward compatibility, though I'm only using kryo-serializers for Guava immutables and Java's UnmodifiableCollection:
```java
UnmodifiableCollectionsSerializer.registerSerializers(kryo);
// Guava
ImmutableListSerializer.registerSerializers(kryo);
ImmutableSetSerializer.registerSerializers(kryo);
ImmutableMapSerializer.registerSerializers(kryo);
ImmutableMultimapSerializer.registerSerializers(kryo);
ReverseListSerializer.registerSerializers(kryo);
```

**Comment by magro** [comment]
@amitsela So does it work?

**Comment by amitsela** [comment]
@magro Seems to... I know for sure that `UnmodifiableCollectionsSerializer`, and `UnmodifiableCollectionsSerializer` work.

**Comment by magro** [comment]
Great!

**Pull request merged**
