### PR TITLE
Add optional trait to protocol-buffers dependency

### LINKED ISSUE #59: Make protocol buffers a separate dependency
I am using a library that requires kryo-serializers as a dependency, called [PaperDb](https://github.com/pilgr/Paper). The library doesn't use any protobuf, but because of this dependency it adds almost ~7k methods because of it. In Android, method count is highly important because it affects app startup time, and some limitations around 65k methods before some VM hackery is required.

Sadly, the dependency cannot be transitively removed by maven/gradle either. I'd like to ask that a separate module is created containing just the protobuf code and dependency, if possible.

### PR DESCRIPTION
**Pull request by pakoito**
Fix #59

### CODE REVIEW

**Comment by magro** [comment]
Thanks for the PR, I'll do a release soon!

**Comment by pakoito** [comment]
Thanks!

**Comment by magro** [comment]
I just released it with 0.39.

**Comment by magro** [comment]
Btw, I now also updated the kryo dependency to 4.0.0 and released kryo-serializers 0.40 with this.

**Pull request merged**
