### PR TITLE
Add Dexx Collection serializers

### PR DESCRIPTION
**Pull request by aaronpoweruser**
Dexx provides Dexx Collections a port of Scala's immutable, persistent collection classes in java.

Test cover the base cases, I can add more if needed.

### CODE REVIEW

**Comment by magro** [comment]
Great PR! Right now a serialized LinkedList would be deserialized as IndexedList, perhaps mention this restriction? The same is probably the case for SortedSet/Map.

**Comment by aaronpoweruser** [comment]
Nice catch, I will make some sorted serializers, they should work as long as, they are added as serializers before the general versions.

**Comment by aaronpoweruser** [comment]
@magro I also have Kotlin versions that wrap the dexx kcollections.  But since kotin is a compile dependency im not sure what the best way to submit them is.

**Comment by magro** [comment]
Couldn't you mark the dependency on kotlin as optional as well?

**Comment by magro** [comment]
Thanks for the PR, I just released it with 0.39.

**Comment by magro** [comment]
Btw, I also just updated the kryo dependency to 4.0.0 and released kryo-serializers 0.40 with this.

**Pull request closed without merging**
